"""make required fields not null

Revision ID: 2f66a1847a92
Revises: 601e6752d1e8
Create Date: 2026-09-19 23:14:18.050152

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "2f66a1847a92"
down_revision: Union[str, Sequence[str], None] = "601e6752d1e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("clients", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("clients", "tariff_plan", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("document_chunks", "document_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("document_chunks", "text_content", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("document_chunks", "embedding", existing_type=Vector(dim=1536), nullable=False)
    op.alter_column("document_chunks", "chunk_index", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("documents", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("documents", "product_category", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("tasks", "query", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tasks", "query", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("documents", "product_category", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("documents", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("document_chunks", "chunk_index", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("document_chunks", "embedding", existing_type=Vector(1536), nullable=True)
    op.alter_column("document_chunks", "text_content", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("document_chunks", "document_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("clients", "tariff_plan", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("clients", "status", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
