[project]
name = "worker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic",
    "python-dotenv",
    "openai",
    "faststream[cli,kafka]>=0.7.5",
    "langchain-core>=1.6.1",
    "langchain-text-splitters>=1.1.2",
    "langchain-google-genai>=4.4.0",
    "asyncpg>=0.31.0",
    "pydantic-settings",
    "sqlalchemy",
    "pgvector",
    "google-genai",
    "tenacity",
    "greenlet>=3.5.5",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_default_test_loop_scope = "session"
asyncio_default_fixture_loop_scope = "session"



[project.scripts]
ingest-docs = "worker_scripts.ingest_docs:cli"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*", "worker_scripts*"]
