[project]
name = "worker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic",
    "python-dotenv",
    "openai",
    "faststream[cli,kafka]>=0.7.5",
    "langchain-core>=1.6.1",
    "langchain-text-splitters>=1.1.2",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
]

[tool.pytest.ini_options]
pythonpath = ["."]
